# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_machine_name', models.CharField(max_length=50)),
                ('inside_ip', models.CharField(max_length=40)),
                ('outside_up', models.CharField(max_length=40)),
                ('service_group', models.CharField(max_length=40)),
                ('cpu_num', models.IntegerField()),
                ('memory_size', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('create_time', models.DateTimeField(verbose_name='create time')),
            ],
        ),
    ]
